name: Run Server Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    working-directory: ./server

jobs:
  test-get-details:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install server dependencies
        run: npm install

      - name: Run server tests
        run: npm test

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: saying goodbye after finished
        run: echo "goodbye for now"
        shell: bash
        