name: Run Server Tests

on:
  push:
    branches:
      - develop

defaults:
  run:
    working-directory: ./server

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install server dependencies
        run: npm install

      - name: Run server tests
        run: npm test
